/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ArchivosInterfaz;

import java.awt.Color;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import java.io.IOException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import sic.cibernet.CatalogoManager;
import sic.cibernet.Cuenta;
import sic.cibernet.LibroMayorTableModel;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import sic.cibernet.Asistencia;
import sic.cibernet.AsistenciaManager;
import sic.cibernet.AsistenciaPDF;
import sic.cibernet.BalanceGeneralTableModel;
import sic.cibernet.Empleado;
import sic.cibernet.EmpleadoManager;
import sic.cibernet.EmpleadoTableModel;
import sic.cibernet.EstadoGeneralPDF;
import sic.cibernet.LibroDiarioTableModel;
import sic.cibernet.RegistroDiario;
import sic.cibernet.RegistroDiarioManager;
/**
 *
 * @author reddarkshadow
 */
public class Base extends javax.swing.JFrame {

    /**
     * Creates new form Base
     */
    RegistroDiarioManager RDM;
    CatalogoManager CM;
    EmpleadoManager EM;
    public Base(String usuario) {
        try {
            // Cambia FlatLightLaf por el tema que quieras usar
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("No se pudo aplicar FlatLaf");
        }
        initComponents();
        this.setLocationRelativeTo(null);
        flg1=false;
        flg2=false;
        flg3=false;
        flg3=false;
        lb_usuario.setText(usuario);
        CM = new CatalogoManager();
        CM.inicializarCatalogo();
        List<Cuenta> ListaCuenta = CM.cargarCuentas();
        LibroMayorTableModel tablemodel = new LibroMayorTableModel(ListaCuenta);
        libro_mayor.setModel(tablemodel);
        RDM = new RegistroDiarioManager();
        List<RegistroDiario> registros = RDM.cargarRegistros();
        LibroDiarioTableModel tablemodel1 = new LibroDiarioTableModel(registros);
        libro_diario.setModel(tablemodel1);
        EM=new EmpleadoManager();
    }
    boolean flg1,flg2,flg3,flg4;
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Ccuentas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Empleados = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_Lcontables = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_RTrans = new javax.swing.JPanel();
        icontrans = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lb_usuario = new javax.swing.JLabel();
        btn_salir = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tb_contenido = new javax.swing.JTabbedPane();
        Transaccion = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_transaccion = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        btn_agregarCuenta = new javax.swing.JButton();
        cmb_tipo = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        btn_guardar = new javax.swing.JButton();
        tf_descripcion = new javax.swing.JTextField();
        btn_nuevo = new javax.swing.JButton();
        cb_ivaDebito = new javax.swing.JCheckBox();
        cb_ivaCredito = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        cmb_cuentas = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        ftf_monto = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        catalogo = new javax.swing.JPanel();
        libros = new javax.swing.JPanel();
        mayor_diario = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        libro_diario = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        libro_mayor = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        general_hoja = new javax.swing.JTable();
        btn_ccc = new javax.swing.JButton();
        Costeo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        resultados_hoja = new javax.swing.JTable();
        empleados = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hoja_empleados = new javax.swing.JTable();
        btn_asistencia = new javax.swing.JButton();
        btn_añadir = new javax.swing.JButton();
        dAsistencia = new javax.swing.JButton();
        Asistencia = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        comboboxTipo = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        registrarAsistencia = new javax.swing.JButton();
        comboBoxEmpleados = new javax.swing.JComboBox<>();
        limpiarAsistencia = new javax.swing.JButton();
        labelFecha = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        horasTrabajadas = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        nombre_Empleado = new javax.swing.JTextField();
        id_empleado = new javax.swing.JTextField();
        salario_hora = new javax.swing.JFormattedTextField();
        jLabel30 = new javax.swing.JLabel();
        area_empleado = new javax.swing.JTextField();
        btn_Guardar = new javax.swing.JButton();
        btn_Nuevo = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        CEMOC = new javax.swing.JFormattedTextField();
        CEMC = new javax.swing.JFormattedTextField();
        CRMC = new javax.swing.JFormattedTextField();
        CRMOC = new javax.swing.JFormattedTextField();
        CRIC = new javax.swing.JFormattedTextField();
        CEMP = new javax.swing.JFormattedTextField();
        CEMOCP = new javax.swing.JFormattedTextField();
        CEIC = new javax.swing.JFormattedTextField();
        CEIP = new javax.swing.JFormattedTextField();
        CRMP = new javax.swing.JFormattedTextField();
        CRIP = new javax.swing.JFormattedTextField();
        CRMOP = new javax.swing.JFormattedTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        btn_Costeo = new javax.swing.JButton();
        rm = new javax.swing.JLabel();
        rci = new javax.swing.JLabel();
        rmo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(3, 17, 56));

        btn_Ccuentas.setBackground(new java.awt.Color(3, 17, 56));
        btn_Ccuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Ccuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CcuentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CcuentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CcuentasMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Catálogo de cuentas");

        jLabel3.setIcon(new javax.swing.ImageIcon("src/img/catalogo.png"));
        jLabel3.setMaximumSize(new java.awt.Dimension(24, 24));
        jLabel3.setMinimumSize(new java.awt.Dimension(24, 24));
        jLabel3.setPreferredSize(new java.awt.Dimension(24, 24));

        javax.swing.GroupLayout btn_CcuentasLayout = new javax.swing.GroupLayout(btn_Ccuentas);
        btn_Ccuentas.setLayout(btn_CcuentasLayout);
        btn_CcuentasLayout.setHorizontalGroup(
            btn_CcuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_CcuentasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_CcuentasLayout.setVerticalGroup(
            btn_CcuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_CcuentasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_CcuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        btn_Empleados.setBackground(new java.awt.Color(3, 17, 56));
        btn_Empleados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EmpleadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EmpleadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EmpleadosMouseExited(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Empleados");

        jLabel8.setIcon(new javax.swing.ImageIcon("src/img/empleado.png"));

        javax.swing.GroupLayout btn_EmpleadosLayout = new javax.swing.GroupLayout(btn_Empleados);
        btn_Empleados.setLayout(btn_EmpleadosLayout);
        btn_EmpleadosLayout.setHorizontalGroup(
            btn_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_EmpleadosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_EmpleadosLayout.setVerticalGroup(
            btn_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_EmpleadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        btn_Lcontables.setBackground(new java.awt.Color(3, 17, 56));
        btn_Lcontables.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Lcontables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LcontablesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LcontablesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LcontablesMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("src/img/libro.png"));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Libros Contables");

        javax.swing.GroupLayout btn_LcontablesLayout = new javax.swing.GroupLayout(btn_Lcontables);
        btn_Lcontables.setLayout(btn_LcontablesLayout);
        btn_LcontablesLayout.setHorizontalGroup(
            btn_LcontablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_LcontablesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_LcontablesLayout.setVerticalGroup(
            btn_LcontablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_LcontablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_LcontablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_RTrans.setBackground(new java.awt.Color(3, 17, 56));
        btn_RTrans.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_RTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_RTransMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_RTransMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_RTransMouseExited(evt);
            }
        });

        icontrans.setIcon(new javax.swing.ImageIcon("src/img/transaction.png"));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Registrar Transaccion");

        javax.swing.GroupLayout btn_RTransLayout = new javax.swing.GroupLayout(btn_RTrans);
        btn_RTrans.setLayout(btn_RTransLayout);
        btn_RTransLayout.setHorizontalGroup(
            btn_RTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_RTransLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(icontrans, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        btn_RTransLayout.setVerticalGroup(
            btn_RTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_RTransLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(btn_RTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(icontrans, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setIcon(new javax.swing.ImageIcon("src/img/usuario.png"));

        lb_usuario.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lb_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lb_usuario.setText("Usuario");

        btn_salir.setBackground(new java.awt.Color(153, 153, 153));
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salirMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("src/img/salir.png"));

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Salir");

        javax.swing.GroupLayout btn_salirLayout = new javax.swing.GroupLayout(btn_salir);
        btn_salir.setLayout(btn_salirLayout);
        btn_salirLayout.setHorizontalGroup(
            btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_salirLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_salirLayout.setVerticalGroup(
            btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_salirLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_usuario)
                .addGap(47, 47, 47)
                .addComponent(btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(lb_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel24.setIcon(new javax.swing.ImageIcon("src/img/logo2.jpeg"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Lcontables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Ccuentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_RTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel24)
                .addGap(48, 48, 48)
                .addComponent(btn_RTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Ccuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Lcontables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 600));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 940, 40));

        Transaccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel12.setText("Registrar Transacción");
        Transaccion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 254, 29));

        jLabel13.setText("Monto Total:");
        Transaccion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel14.setText("Descripción:");
        Transaccion.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        tabla_transaccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuenta", "Debe", "Haber"
            }
        ));
        tabla_transaccion.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla_transaccion);

        Transaccion.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 630, 187));

        jLabel15.setText("Cuenta ID: ");
        Transaccion.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        btn_agregarCuenta.setText("Agregar Cuenta");
        btn_agregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarCuentaActionPerformed(evt);
            }
        });
        Transaccion.add(btn_agregarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Debe", "Haber" }));
        Transaccion.add(cmb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));
        Transaccion.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 930, 10));

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        Transaccion.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, -1, -1));

        tf_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_descripcionActionPerformed(evt);
            }
        });
        Transaccion.add(tf_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 306, -1));

        btn_nuevo.setText("Nuevo");
        btn_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nuevoMouseClicked(evt);
            }
        });
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        Transaccion.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, -1, -1));

        cb_ivaDebito.setText(" IVA Debito");
        Transaccion.add(cb_ivaDebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        cb_ivaCredito.setText(" IVA Credito");
        cb_ivaCredito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_ivaCreditoMouseClicked(evt);
            }
        });
        cb_ivaCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ivaCreditoActionPerformed(evt);
            }
        });
        Transaccion.add(cb_ivaCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel6.setText("Incluir:");
        Transaccion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        cmb_cuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1101 Caja", "1102 Bancos", "1103 Inventario", "1104 Cuentas por Cobrar", "1105 Licencias de Software", "1106 IVA Crédito Fiscal", "1201 Equipos de Cómputo", "1202 Equipos de Impresión y Escaneo", "1203 Servidores y Equipos de Red", "1204 Mobiliario y Equipo de Oficina", "1205 Mejoras al Inmueble", "2101 Proveedores", "2102 IVA Débito Fiscal", "2103 Préstamos Bancarios", "3101 Capital", "3102 Utilidad del Ejercicio,Capital", "4101 Ingresos por Acceso a Internet", "4102 Ingresos por Servicios de Impresión y Escaneo", "4103 Ingresos por Venta de Accesorios", "4104 Otros Ingresos", "5101 Costo de Ventas de Accesorios", "5201 Gastos de Sueldos y Salarios", "5202 Gastos de Mantenimiento de Equipos", "5203 Gastos de Suministros", "5204 Gastos de Licencias de Software", "5205 Servicios Públicos", "5206 Gastos de Depreciación", "5207 Gastos de Amortización", "5208 Pérdidas en Copias" }));
        Transaccion.add(cmb_cuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 230, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("src/img/transactionG.png"));
        Transaccion.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        ftf_monto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        Transaccion.add(ftf_monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 100, -1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Transaccion.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -30, -1, -1));

        tb_contenido.addTab("0", Transaccion);

        catalogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tb_contenido.addTab("1", catalogo);

        mayor_diario.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        libro_diario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Descripcion", "Cuenta", "Debe", "Haber"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(libro_diario);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
        );

        mayor_diario.addTab("Diario", jPanel8);

        libro_mayor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(libro_mayor);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
        );

        mayor_diario.addTab("Mayor", jPanel9);

        general_hoja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cuenta", "Debe", "Haber"
            }
        ));
        jScrollPane3.setViewportView(general_hoja);

        btn_ccc.setText("Cerrar Ciclo Contable");
        btn_ccc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cccMouseClicked(evt);
            }
        });
        btn_ccc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cccActionPerformed(evt);
            }
        });

        Costeo.setText("Costeo");
        Costeo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CosteoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btn_ccc)
                .addGap(40, 40, 40)
                .addComponent(Costeo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ccc)
                    .addComponent(Costeo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mayor_diario.addTab("General", jPanel2);

        resultados_hoja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cuenta", "Debe", "Haber"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(resultados_hoja);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mayor_diario.addTab("Resultados", jPanel5);

        javax.swing.GroupLayout librosLayout = new javax.swing.GroupLayout(libros);
        libros.setLayout(librosLayout);
        librosLayout.setHorizontalGroup(
            librosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(librosLayout.createSequentialGroup()
                .addComponent(mayor_diario, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        librosLayout.setVerticalGroup(
            librosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(librosLayout.createSequentialGroup()
                .addComponent(mayor_diario, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tb_contenido.addTab("2", libros);

        jLabel17.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel17.setText("Nomina Empleados");

        hoja_empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Area", "Puesto", "Salario"
            }
        ));
        jScrollPane2.setViewportView(hoja_empleados);

        btn_asistencia.setText("Asistencia");
        btn_asistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_asistenciaMouseClicked(evt);
            }
        });
        btn_asistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asistenciaActionPerformed(evt);
            }
        });

        btn_añadir.setText("Añadir");
        btn_añadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_añadirMouseClicked(evt);
            }
        });

        dAsistencia.setText("Descargar Asistencia");
        dAsistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dAsistenciaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout empleadosLayout = new javax.swing.GroupLayout(empleados);
        empleados.setLayout(empleadosLayout);
        empleadosLayout.setHorizontalGroup(
            empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empleadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_añadir)
                .addGap(366, 366, 366)
                .addComponent(btn_asistencia)
                .addGap(60, 60, 60)
                .addComponent(dAsistencia)
                .addGap(43, 43, 43))
            .addGroup(empleadosLayout.createSequentialGroup()
                .addGroup(empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empleadosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel17))
                    .addGroup(empleadosLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        empleadosLayout.setVerticalGroup(
            empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empleadosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empleadosLayout.createSequentialGroup()
                        .addComponent(dAsistencia)
                        .addGap(90, 90, 90))
                    .addGroup(empleadosLayout.createSequentialGroup()
                        .addGroup(empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_asistencia)
                            .addComponent(btn_añadir))
                        .addGap(79, 79, 79))))
        );

        tb_contenido.addTab("3", empleados);

        Asistencia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel18.setText("Asistencia Empleados");
        Asistencia.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabel19.setText("Fecha:");
        Asistencia.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jLabel20.setText("Empleado:");
        Asistencia.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));
        Asistencia.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 66, -1, -1));

        comboboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trabajo", "Vacación", "Permiso Medico", "Ausencia" }));
        Asistencia.add(comboboxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        jLabel22.setText("Tipo:");
        Asistencia.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        jLabel23.setText("Horas Trabajadas:");
        Asistencia.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, 30));

        registrarAsistencia.setText("Registrar");
        registrarAsistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarAsistenciaMouseClicked(evt);
            }
        });
        registrarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarAsistenciaActionPerformed(evt);
            }
        });
        Asistencia.add(registrarAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, -1, -1));

        comboBoxEmpleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Asistencia.add(comboBoxEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 160, -1));

        limpiarAsistencia.setText("Limpiar");
        Asistencia.add(limpiarAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        labelFecha.setText("01/10/204");
        Asistencia.add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon("src/img/asistencia.png"));
        Asistencia.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        horasTrabajadas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        horasTrabajadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horasTrabajadasActionPerformed(evt);
            }
        });
        Asistencia.add(horasTrabajadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        tb_contenido.addTab("A", Asistencia);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel26.setText("Agregar Empleado");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabel27.setText("Nombre:");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel28.setText("ID:");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        jLabel29.setText("Salario por Hora:");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));
        jPanel4.add(nombre_Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 140, -1));
        jPanel4.add(id_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 140, -1));

        salario_hora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jPanel4.add(salario_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 100, -1));

        jLabel30.setText("Area:");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));
        jPanel4.add(area_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 160, -1));

        btn_Guardar.setText("Guardar");
        btn_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GuardarMouseClicked(evt);
            }
        });
        jPanel4.add(btn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        btn_Nuevo.setText("Nuevo");
        btn_Nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_NuevoMouseClicked(evt);
            }
        });
        jPanel4.add(btn_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon("src/img/empleado2.png"));
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        tb_contenido.addTab("E", jPanel4);

        jLabel25.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel25.setText("Costeo Estandar");

        jLabel33.setText("Costo Estandar Materiales:");

        jLabel34.setText("Costo Estandar Mano de Obra:");

        jLabel35.setText("Costo Estandar Indirectos:");

        jLabel36.setText("Costos Reales Materiales:");

        jLabel37.setText("Costos Reales Mano de Obra:");

        jLabel38.setText("Costos Reales Indirectos:");

        CEMOC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        CEMC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        CRMC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        CRMOC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        CRIC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        CEMP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        CEMOCP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        CEIC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        CEIP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        CRMP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        CRIP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        CRMOP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel39.setText("Cantidad");

        jLabel40.setText("P/U");

        btn_Costeo.setText("Calcular");
        btn_Costeo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CosteoMouseClicked(evt);
            }
        });

        rm.setText("Resultado Materiales: ");

        rci.setText("Resultado Costos Indirectos:");

        rmo.setText("Resultado Mano de Obra:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel25))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel34)
                                .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel33))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(CRIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CRIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(CRMOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CRMOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addComponent(CRMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CRMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addComponent(CEIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CEIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addComponent(CEMOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CEMOCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                        .addComponent(CEMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabel39)
                                        .addGap(36, 36, 36)))
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CEMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabel40)
                                        .addGap(24, 24, 24)))))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btn_Costeo))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rmo)
                                    .addComponent(rm)
                                    .addComponent(rci))))))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel25)
                .addGap(45, 45, 45)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(CEMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CEMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(CEMOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CEMOCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(rm)
                        .addGap(18, 18, 18)
                        .addComponent(rmo)
                        .addGap(18, 18, 18)
                        .addComponent(rci)))
                .addGap(16, 16, 16)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(CEIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CEIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(CRMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CRMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(CRMOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CRMOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel38))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CRIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CRIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Costeo)))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        tb_contenido.addTab("C", jPanel10);

        getContentPane().add(tb_contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 2, 940, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_RTransMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RTransMouseEntered
        if(!flg1){
            btn_RTrans.setBackground(new Color(0,204,153));
        }
    }//GEN-LAST:event_btn_RTransMouseEntered

    private void btn_RTransMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RTransMouseExited
        if(!flg1){
            btn_RTrans.setBackground(new Color(3,17,56));
        }
    }//GEN-LAST:event_btn_RTransMouseExited

    private void btn_RTransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RTransMouseClicked
        // TODO add your handling code here:
        flg1=true;
        flg2=false;
        flg3=false;
        flg4=false;
        btn_Empleados.setBackground(new Color(3,17,56));
        btn_Ccuentas.setBackground(new Color(3,17,56));
        btn_Lcontables.setBackground(new Color(3,17,56));
        btn_RTrans.setBackground(new Color(255,102,51));
        tb_contenido.setSelectedIndex(0);
        
    }//GEN-LAST:event_btn_RTransMouseClicked

    private void btn_CcuentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CcuentasMouseEntered
        // TODO add your handling code here:
        if(!flg2){
            btn_Ccuentas.setBackground(new Color(0,204,153));
        }
    }//GEN-LAST:event_btn_CcuentasMouseEntered

    private void btn_CcuentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CcuentasMouseExited
        // TODO add your handling code here:
        if(!flg2){
            btn_Ccuentas.setBackground(new Color(3,17,56));
        }
    }//GEN-LAST:event_btn_CcuentasMouseExited

    private void btn_CcuentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CcuentasMouseClicked
        // TODO add your handling code here:
        flg1=false;
        flg2=true;
        flg3=false;
        flg4=false;
        btn_Empleados.setBackground(new Color(3,17,56));
        btn_Ccuentas.setBackground(new Color(255,102,51));
        btn_Lcontables.setBackground(new Color(3,17,56));
        btn_RTrans.setBackground(new Color(3,17,56));
        tb_contenido.setSelectedIndex(1);
        
    }//GEN-LAST:event_btn_CcuentasMouseClicked

    private void btn_LcontablesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LcontablesMouseEntered
        // TODO add your handling code here:
        if(!flg3){
            btn_Lcontables.setBackground(new Color(0,204,153));
        }
    }//GEN-LAST:event_btn_LcontablesMouseEntered

    private void btn_LcontablesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LcontablesMouseExited
        // TODO add your handling code here:
        if(!flg3){
            btn_Lcontables.setBackground(new Color(3,17,56));
        }
    }//GEN-LAST:event_btn_LcontablesMouseExited
    
    private void btn_LcontablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LcontablesMouseClicked
        // TODO add your handling code here:
        flg1=false;
        flg2=false;
        flg3=true;
        flg4=false;
        btn_Empleados.setBackground(new Color(3,17,56));
        btn_Ccuentas.setBackground(new Color(3,17,56));
        btn_Lcontables.setBackground(new Color(255,102,51));
        btn_RTrans.setBackground(new Color(3,17,56));
        tb_contenido.setSelectedIndex(2);
    }//GEN-LAST:event_btn_LcontablesMouseClicked

    private void btn_EmpleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpleadosMouseEntered
        // TODO add your handling code here:
        if(!flg4){
            btn_Empleados.setBackground(new Color(0,204,153));
        }
    }//GEN-LAST:event_btn_EmpleadosMouseEntered

    private void btn_EmpleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpleadosMouseExited
        // TODO add your handling code here:
        if(!flg4){
            btn_Empleados.setBackground(new Color(3,17,56));
        }
    }//GEN-LAST:event_btn_EmpleadosMouseExited

    private void btn_EmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpleadosMouseClicked
        // TODO add your handling code here:
        flg1=false;
        flg2=false;
        flg3=false;
        flg4=true;
        btn_Empleados.setBackground(new Color(255,102,51));
        btn_Ccuentas.setBackground(new Color(3,17,56));
        btn_Lcontables.setBackground(new Color(3,17,56));
        btn_RTrans.setBackground(new Color(3,17,56));
        tb_contenido.setSelectedIndex(3);
        List<Empleado> empleados = EM.cargarEmpleados();

        // Crear el TableModel y el JTable
        EmpleadoTableModel model = new EmpleadoTableModel(empleados);
        hoja_empleados.setModel(model);
    }//GEN-LAST:event_btn_EmpleadosMouseClicked

    private void btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseEntered
        btn_salir.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_btn_salirMouseEntered

    private void btn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseExited
        // TODO add your handling code here:
        btn_salir.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn_salirMouseExited

    private void btn_agregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarCuentaActionPerformed
        // Agrega las cuentas y el monto a la tabla de transaccion
        try {
            String cuenta = (String) cmb_cuentas.getSelectedItem();
            double valor = ((Number) ftf_monto.getValue()).doubleValue();
            if(cmb_tipo.getSelectedIndex()==1){
                if(cb_ivaCredito.isSelected()){
                    String cuentaiva ="1106 IVA Crédito Fiscal";
                    double monto=(valor/1.13);
                    BigDecimal bd = new BigDecimal(monto).setScale(2, RoundingMode.HALF_UP);
                    monto = bd.doubleValue();
                    double ivadebe = valor-monto;
                    BigDecimal bdi = new BigDecimal(ivadebe).setScale(2, RoundingMode.HALF_UP);
                    ivadebe = bdi.doubleValue();
                    double ivahaber = 0.00;
                    double debe = monto;
                    double haber =0;
                    Object[] row ={cuenta,debe,haber};
                    Object[] row2 ={cuentaiva,ivadebe,ivahaber};
                    DefaultTableModel model = (DefaultTableModel) tabla_transaccion.getModel();
                    model.addRow(row);
                    model.addRow(row2);
                } else if(cb_ivaDebito.isSelected()){
                    String cuentaiva ="2102 IVA Débito Fiscal";
                    double monto=(valor/1.13);
                    BigDecimal bd = new BigDecimal(monto).setScale(2, RoundingMode.HALF_UP);
                    monto = bd.doubleValue();
                    double ivadebe =0.0;
                    double ivahaber =valor-monto;
                    BigDecimal bdi = new BigDecimal(ivahaber).setScale(2, RoundingMode.HALF_UP);
                    ivahaber = bdi.doubleValue();
                    double debe = monto;
                    double haber =0;
                    Object[] row ={cuenta,debe,haber};
                    Object[] row2 ={cuentaiva,ivadebe,ivahaber};
                    DefaultTableModel model = (DefaultTableModel) tabla_transaccion.getModel();
                    model.addRow(row);
                    model.addRow(row2);
                }else{
                    double debe = valor;
                    double haber =0;
                    Object[] row ={cuenta,debe,haber};   
                    DefaultTableModel model = (DefaultTableModel) tabla_transaccion.getModel();
                    model.addRow(row);  
                }
                
            }else if(cmb_tipo.getSelectedIndex()== 2){
                
                if(cb_ivaCredito.isSelected()){
                    String cuentaiva ="1106 IVA Crédito Fiscal";
                    double monto = valor/1.13;
                    BigDecimal bd = new BigDecimal(monto).setScale(2, RoundingMode.HALF_UP);
                    monto = bd.doubleValue();
                    double ivadebe = valor-monto;
                    BigDecimal bdi = new BigDecimal(ivadebe).setScale(2, RoundingMode.HALF_UP);
                    ivadebe = bdi.doubleValue();
                    double ivahaber = 0.00;
                    double debe = 0.00;
                    double haber =monto;
                    Object[] row ={cuenta,debe,haber};
                    Object[] row2 ={cuentaiva,ivadebe,ivahaber};
                    DefaultTableModel model = (DefaultTableModel) tabla_transaccion.getModel();
                    model.addRow(row);
                    model.addRow(row2);
                } else if(cb_ivaDebito.isSelected()){
                    String cuentaiva ="2102 IVA Débito Fiscal";
                    double monto=(valor/1.13);
                    BigDecimal bd = new BigDecimal(monto).setScale(2, RoundingMode.HALF_UP);
                    monto = bd.doubleValue();
                    double ivadebe =0.0;
                    double ivahaber = valor-monto;
                    BigDecimal bdi = new BigDecimal(ivahaber).setScale(2, RoundingMode.HALF_UP);
                    ivahaber = bdi.doubleValue();
                    double debe = 0;
                    double haber =monto;
                    Object[] row ={cuenta,debe,haber};
                    Object[] row2 ={cuentaiva,ivadebe,ivahaber};
                    DefaultTableModel model = (DefaultTableModel) tabla_transaccion.getModel();
                    model.addRow(row);
                    model.addRow(row2);
                }else{
                    double debe =0;
                    double haber =valor;
                    Object[] row ={cuenta,debe,haber};   
                    DefaultTableModel model = (DefaultTableModel) tabla_transaccion.getModel();
                    model.addRow(row);  
                }
            }
            
        } catch (NullPointerException | ClassCastException e) {
                
        }


    }//GEN-LAST:event_btn_agregarCuentaActionPerformed

    private void tf_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_descripcionActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void registrarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarAsistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarAsistenciaActionPerformed

    private void btn_asistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_asistenciaActionPerformed

    private void btn_asistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_asistenciaMouseClicked
        tb_contenido.setSelectedIndex(4);
        comboBoxEmpleados.removeAllItems(); // Limpia los elementos existentes
        List<Empleado> empleados = EM.cargarEmpleados();

        for (Empleado empleado : empleados) {
            comboBoxEmpleados.addItem(empleado.getNombre());
        }
        
        LocalDate fechaActual = LocalDate.now();
        labelFecha.setText(fechaActual.toString());
    }//GEN-LAST:event_btn_asistenciaMouseClicked

    private void cb_ivaCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ivaCreditoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cb_ivaCreditoActionPerformed

    private void cb_ivaCreditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_ivaCreditoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_ivaCreditoMouseClicked

    private void btn_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nuevoMouseClicked
        // Resetea los campos de transaccion:
        DefaultTableModel model = (DefaultTableModel) tabla_transaccion.getModel();
        tf_descripcion.setText("");
        cmb_cuentas.setSelectedIndex(0);
        cmb_tipo.setSelectedIndex(0);
        ftf_monto.setText("");
        cb_ivaCredito.setSelected(false);
        cb_ivaDebito.setSelected(false);
        model.setRowCount(0);
    }//GEN-LAST:event_btn_nuevoMouseClicked

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        
        String descripcion = tf_descripcion.getText();
        for (int i = 0; i < tabla_transaccion.getRowCount(); i++) {
            String cuenta = (String) tabla_transaccion.getValueAt(i, 0);
            int espacioIndex = cuenta.indexOf(" ");
            String numero = cuenta.substring(0, espacioIndex);
            //System.out.println("Número: " + numero);
            double debe = (double) tabla_transaccion.getValueAt(i, 1);
            double haber = (double) tabla_transaccion.getValueAt(i, 2);
            RDM.agregarRegistro(cuenta, debe, haber, descripcion);
            List<Cuenta> ListaCuenta = CM.cargarCuentas();
            for(Cuenta c: ListaCuenta) {
                if(c.getIdCuenta().equals(numero)){
                    if(debe==0.0){
                        c.setHaber(haber);
                    }else{
                        c.setDebe(debe);
                    }
                }
                c.actualizar();
            }
            try {
                CM.guardarCuentas(ListaCuenta);
            } catch (IOException ex) {
                Logger.getLogger(Base.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        List<RegistroDiario> registros = RDM.cargarRegistros();
        LibroDiarioTableModel tablemodel = new LibroDiarioTableModel(registros);
        libro_diario.setModel(tablemodel);
        List<Cuenta> ListaCuenta = CM.cargarCuentas();
        LibroMayorTableModel tablemodel1 = new LibroMayorTableModel(ListaCuenta);
        libro_mayor.setModel(tablemodel1);
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_cccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cccActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_cccActionPerformed

    private void btn_cccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cccMouseClicked
        // TODO add your handling code here:
        List<Cuenta> ListaCuenta = CM.cargarCuentas();
        for(Cuenta c: ListaCuenta) {
            c.cerrarCuenta();
        }
        try {
            CM.guardarCuentas(ListaCuenta);
        } catch (IOException ex) {
            Logger.getLogger(Base.class.getName()).log(Level.SEVERE, null, ex);
        }
        // IDs específicos de las cuentas que queremos mostrar
        String[] idsFiltrados = {"4101", "4102", "4103", "4104", "5101", "5201", "5202", "5203", "5204", "5205", "5206", "5207"};

        // Filtrar las cuentas con los IDs específicos
        List<Cuenta> cuentasFiltradas = ListaCuenta.stream()
                .filter(cuenta -> java.util.Arrays.asList(idsFiltrados).contains(cuenta.getIdCuenta()))
                .collect(Collectors.toList());

        // Crear el modelo de la tabla con las columnas Cuenta, Debe, Haber
        DefaultTableModel model = new DefaultTableModel(new Object[]{"Cuenta", "Debe", "Haber"}, 0);

        // Variables para calcular los totales de "Debe" y "Haber"
        double totalDebe = 0;
        double totalHaber = 0;

        // Agregar las cuentas filtradas al modelo de la tabla y calcular los totales
        for (Cuenta cuenta : cuentasFiltradas) {
            // Asegurarse de usar el nombre de la cuenta
            model.addRow(new Object[]{cuenta.getNombre(), cuenta.getDebe(), cuenta.getHaber()});
            totalDebe += cuenta.getDebe();
            totalHaber += cuenta.getHaber();
        }

        // Agregar la fila "Total" con la suma de las columnas Debe y Haber
        model.addRow(new Object[]{"Total", totalDebe, totalHaber});

        // Calcular la utilidad como Haber - Debe y agregarla en la última fila
        double utilidad = totalHaber - totalDebe;
        model.addRow(new Object[]{"Utilidad", "", utilidad});
        resultados_hoja.setModel(model);
        
        
        
        // Actualizar Utilidad y crear el balance general
        //recuperando las cuentas
        List<Cuenta> ListaCuenta2 = CM.cargarCuentas();
        //Buscando y guardando
        for (Cuenta cuenta : ListaCuenta2) {
            // Asegurarse de usar el nombre de la cuenta
            if(cuenta.getIdCuenta().equals("3102")){
                cuenta.setHaber(utilidad);
            }
        }
        //Guardando
        try {
            CM.guardarCuentas(ListaCuenta);
        } catch (IOException ex) {
            Logger.getLogger(Base.class.getName()).log(Level.SEVERE, null, ex);
        }
        List<Cuenta> ListaCuenta1 = CM.cargarCuentas();
        BalanceGeneralTableModel tablemodelC= new BalanceGeneralTableModel(ListaCuenta1);
        general_hoja.setModel(tablemodelC);
        LibroMayorTableModel tablemodel1 = new LibroMayorTableModel(ListaCuenta1);
        libro_mayor.setModel(tablemodel1);
        
    }//GEN-LAST:event_btn_cccMouseClicked

    private void horasTrabajadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horasTrabajadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horasTrabajadasActionPerformed

    private void btn_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GuardarMouseClicked
        String id = id_empleado.getText();
        String nombre = nombre_Empleado.getText();
        String area = area_empleado.getText();
        double salarioHora = ((Number) salario_hora.getValue()).doubleValue();
        EM.agregarEmpleado(id, nombre, area, salarioHora);
        List<Empleado> empleados = EM.cargarEmpleados();

        // Crear el TableModel y el JTable
        EmpleadoTableModel model = new EmpleadoTableModel(empleados);
        hoja_empleados.setModel(model);
    }//GEN-LAST:event_btn_GuardarMouseClicked

    private void btn_añadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_añadirMouseClicked
        // TODO add your handling code here:
        tb_contenido.setSelectedIndex(5);
    }//GEN-LAST:event_btn_añadirMouseClicked

    private void btn_NuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NuevoMouseClicked
        id_empleado.setText("");
        nombre_Empleado.setText("");
        area_empleado.setText("");
        salario_hora.setText("");
    }//GEN-LAST:event_btn_NuevoMouseClicked

    private void registrarAsistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarAsistenciaMouseClicked
        // TODO add your handling code here:
        String nombre = (String) comboBoxEmpleados.getSelectedItem();
        String tipo = (String) comboboxTipo.getSelectedItem();
        double hTrabajadas = ((Number)  horasTrabajadas.getValue()).doubleValue();
        LocalDate fechaActual = LocalDate.now();
        AsistenciaManager AM = new AsistenciaManager();
        AM.registrarAsistencia(nombre, fechaActual, tipo);
        //Falta Registrar el salario en las cuentas
       
    }//GEN-LAST:event_registrarAsistenciaMouseClicked

    private void dAsistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dAsistenciaMouseClicked
        // TODO add your handling code here:
        AsistenciaManager AM = new AsistenciaManager();
        List<Asistencia> asistencias = AM.cargarAsistencias();
        AsistenciaPDF apdf = new AsistenciaPDF();
        apdf.generarPDF(asistencias);
        
    }//GEN-LAST:event_dAsistenciaMouseClicked

    private void btn_CosteoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CosteoMouseClicked
        // TODO add your handling code here:
        double Psm = ((Number) CEMP.getValue()).doubleValue();
        double Prm = ((Number) CRMP.getValue()).doubleValue();
        double Crm = ((Number) CRMC.getValue()).doubleValue();
        double Csm = ((Number) CEMC.getValue()).doubleValue();
        //Fin Costeo Materiales
        double Psmo = ((Number) CEMOCP.getValue()).doubleValue();
        double Prmo = ((Number) CRMOP.getValue()).doubleValue();
        double Crmo = ((Number) CRMOC.getValue()).doubleValue();
        double Csmo = ((Number) CEMOC.getValue()).doubleValue();
        //Fin Costeo Mano de Obra
        double Psci = ((Number) CEIP.getValue()).doubleValue();
        double Prci = ((Number) CRIP.getValue()).doubleValue();
        double Crci = ((Number) CRIC.getValue()).doubleValue();
        double Csci = ((Number) CEIC.getValue()).doubleValue();
        
        double vm = ((Psm-Prm)*Crm)+((Csm-Crm)*Psm);
        double vmo = ((Psmo-Prmo)*Crmo)+((Csmo-Crmo)*Psmo);
        double vci = ((Psci-Prci)*Crci)+((Csci-Crci)*Psci);
        BigDecimal vm1 = new BigDecimal(vm).setScale(2, RoundingMode.HALF_UP);
        vm=vm1.doubleValue();
        BigDecimal vmo1 = new BigDecimal(vmo).setScale(2, RoundingMode.HALF_UP);
        vmo=vmo1.doubleValue();
        BigDecimal vc1 = new BigDecimal(vci).setScale(2, RoundingMode.HALF_UP);
        vci=vc1.doubleValue();
        
        rm.setText("Resultado Materiales: "+vm);
        rmo.setText("Resultado Materiales: "+vmo);
        rci.setText("Resultado Materiales: "+vci);
        
        
    }//GEN-LAST:event_btn_CosteoMouseClicked

    private void CosteoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CosteoMouseClicked
        // TODO add your handling code here:
        tb_contenido.setSelectedIndex(6);
    }//GEN-LAST:event_CosteoMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Asistencia;
    private javax.swing.JFormattedTextField CEIC;
    private javax.swing.JFormattedTextField CEIP;
    private javax.swing.JFormattedTextField CEMC;
    private javax.swing.JFormattedTextField CEMOC;
    private javax.swing.JFormattedTextField CEMOCP;
    private javax.swing.JFormattedTextField CEMP;
    private javax.swing.JFormattedTextField CRIC;
    private javax.swing.JFormattedTextField CRIP;
    private javax.swing.JFormattedTextField CRMC;
    private javax.swing.JFormattedTextField CRMOC;
    private javax.swing.JFormattedTextField CRMOP;
    private javax.swing.JFormattedTextField CRMP;
    private javax.swing.JButton Costeo;
    private javax.swing.JPanel Transaccion;
    private javax.swing.JTextField area_empleado;
    private javax.swing.JPanel btn_Ccuentas;
    private javax.swing.JButton btn_Costeo;
    private javax.swing.JPanel btn_Empleados;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JPanel btn_Lcontables;
    private javax.swing.JButton btn_Nuevo;
    private javax.swing.JPanel btn_RTrans;
    private javax.swing.JButton btn_agregarCuenta;
    private javax.swing.JButton btn_asistencia;
    private javax.swing.JButton btn_añadir;
    private javax.swing.JButton btn_ccc;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JPanel btn_salir;
    private javax.swing.JPanel catalogo;
    private javax.swing.JCheckBox cb_ivaCredito;
    private javax.swing.JCheckBox cb_ivaDebito;
    private javax.swing.JComboBox<String> cmb_cuentas;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JComboBox<String> comboBoxEmpleados;
    private javax.swing.JComboBox<String> comboboxTipo;
    private javax.swing.JButton dAsistencia;
    private javax.swing.JPanel empleados;
    private javax.swing.JFormattedTextField ftf_monto;
    private javax.swing.JTable general_hoja;
    private javax.swing.JTable hoja_empleados;
    private javax.swing.JFormattedTextField horasTrabajadas;
    private javax.swing.JLabel icontrans;
    private javax.swing.JTextField id_empleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JTable libro_diario;
    private javax.swing.JTable libro_mayor;
    private javax.swing.JPanel libros;
    private javax.swing.JButton limpiarAsistencia;
    private javax.swing.JTabbedPane mayor_diario;
    private javax.swing.JTextField nombre_Empleado;
    private javax.swing.JLabel rci;
    private javax.swing.JButton registrarAsistencia;
    private javax.swing.JTable resultados_hoja;
    private javax.swing.JLabel rm;
    private javax.swing.JLabel rmo;
    private javax.swing.JFormattedTextField salario_hora;
    private javax.swing.JTable tabla_transaccion;
    private javax.swing.JTabbedPane tb_contenido;
    private javax.swing.JTextField tf_descripcion;
    // End of variables declaration//GEN-END:variables
}
