/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ArchivosInterfaz;

import java.awt.Color;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import sic.cibernet.LogSeguro;
/**
 *
 * @author reddarkshadow
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_der = new javax.swing.JPanel();
        lb_iniciarsesison = new javax.swing.JLabel();
        lb_usuario = new javax.swing.JLabel();
        lb_contraseña = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_verificar = new javax.swing.JPanel();
        lb_verificar = new javax.swing.JLabel();
        textf_usuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        pf_contraseña = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        panel_izq = new javax.swing.JPanel();
        lb_logo = new javax.swing.JLabel();
        lb_imagen = new javax.swing.JLabel();
        lb_slogan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_der.setBackground(new java.awt.Color(255, 255, 255));
        panel_der.setForeground(new java.awt.Color(204, 0, 0));

        lb_iniciarsesison.setFont(new java.awt.Font("0xProto Nerd Font Propo", 1, 14)); // NOI18N
        lb_iniciarsesison.setText("INICIAR SESIÓN");

        lb_usuario.setText("Usuario");

        lb_contraseña.setText("Contraseña");

        jSeparator1.setForeground(new java.awt.Color(153, 0, 0));

        btn_verificar.setBackground(java.awt.Color.lightGray);
        btn_verificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_verificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_verificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_verificarMouseExited(evt);
            }
        });

        lb_verificar.setBackground(new java.awt.Color(153, 153, 255));
        lb_verificar.setFont(new java.awt.Font("0xProto Nerd Font Propo", 1, 12)); // NOI18N
        lb_verificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_verificar.setText("Verificar");
        lb_verificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btn_verificarLayout = new javax.swing.GroupLayout(btn_verificar);
        btn_verificar.setLayout(btn_verificarLayout);
        btn_verificarLayout.setHorizontalGroup(
            btn_verificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_verificarLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(lb_verificar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btn_verificarLayout.setVerticalGroup(
            btn_verificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_verificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        textf_usuario.setFont(new java.awt.Font("Liberation Serif", 2, 13)); // NOI18N
        textf_usuario.setForeground(new java.awt.Color(153, 153, 153));
        textf_usuario.setText("Ingrese su usuario");
        textf_usuario.setBorder(null);
        textf_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textf_usuarioMouseClicked(evt);
            }
        });

        pf_contraseña.setForeground(new java.awt.Color(153, 153, 153));
        pf_contraseña.setText("Ingresecontra");
        pf_contraseña.setBorder(null);
        pf_contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pf_contraseñaMouseClicked(evt);
            }
        });
        pf_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_contraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_derLayout = new javax.swing.GroupLayout(panel_der);
        panel_der.setLayout(panel_derLayout);
        panel_derLayout.setHorizontalGroup(
            panel_derLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_derLayout.createSequentialGroup()
                .addGroup(panel_derLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_derLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_derLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panel_derLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_usuario)
                            .addComponent(lb_contraseña)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_derLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btn_verificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_derLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lb_iniciarsesison)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panel_derLayout.setVerticalGroup(
            panel_derLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_derLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(lb_iniciarsesison)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_contraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_verificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        getContentPane().add(panel_der, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 330, 440));

        panel_izq.setBackground(new java.awt.Color(3, 17, 56));
        panel_izq.setForeground(new java.awt.Color(0, 0, 59));

        lb_logo.setFont(new java.awt.Font("Liberation Serif", 3, 13)); // NOI18N
        lb_logo.setForeground(new java.awt.Color(255, 255, 255));
        lb_logo.setText("CIBERNET S.A DE S.V");

        lb_imagen.setIcon(new javax.swing.ImageIcon("src/img/logo.jpeg"));
        lb_imagen.setMaximumSize(new java.awt.Dimension(250, 250));
        lb_imagen.setMinimumSize(new java.awt.Dimension(250, 250));
        lb_imagen.setPreferredSize(new java.awt.Dimension(250, 250));

        lb_slogan.setFont(new java.awt.Font("Bitstream Charter", 2, 13)); // NOI18N
        lb_slogan.setForeground(new java.awt.Color(255, 255, 255));
        lb_slogan.setText("\"Velocidad y comodidad en cada clic\"");

        javax.swing.GroupLayout panel_izqLayout = new javax.swing.GroupLayout(panel_izq);
        panel_izq.setLayout(panel_izqLayout);
        panel_izqLayout.setHorizontalGroup(
            panel_izqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_izqLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(panel_izqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_izqLayout.createSequentialGroup()
                        .addComponent(lb_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_izqLayout.createSequentialGroup()
                        .addComponent(lb_logo)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_izqLayout.createSequentialGroup()
                        .addComponent(lb_slogan)
                        .addGap(81, 81, 81))))
        );
        panel_izqLayout.setVerticalGroup(
            panel_izqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_izqLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(lb_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_logo)
                .addGap(18, 18, 18)
                .addComponent(lb_slogan)
                .addGap(57, 57, 57))
        );

        getContentPane().add(panel_izq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pf_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_contraseñaActionPerformed

    private void textf_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textf_usuarioMouseClicked
        // Si se da click borra el texto por defecto
        textf_usuario.setText("");
        String pf =new String(pf_contraseña.getPassword());
        if(pf.equals("")){
            pf_contraseña.setText("Ingresecontra");
        }
    }//GEN-LAST:event_textf_usuarioMouseClicked

    private void pf_contraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_contraseñaMouseClicked
         // Si se da click borra el texto por defecto
         pf_contraseña.setText("");
         String usuario = new String(textf_usuario.getText());
         if(usuario.equals("")){
             textf_usuario.setText("Ingrese su usuario");
         }
    }//GEN-LAST:event_pf_contraseñaMouseClicked

    private void btn_verificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verificarMouseEntered
        // Cambia el color:
        btn_verificar.setBackground(Color.cyan);
    }//GEN-LAST:event_btn_verificarMouseEntered

    private void btn_verificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verificarMouseExited
        // TODO add your handling code here:
        btn_verificar.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btn_verificarMouseExited

    private void btn_verificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verificarMouseClicked
        String pf =new String(pf_contraseña.getPassword()).trim();
        String usuario = new String(textf_usuario.getText()).trim();        
        try {
            boolean isAuthenticated = LogSeguro.verifyUser(usuario, pf);
            if (isAuthenticated) {
                Base base =new Base(usuario);
                this.dispose();
                base.setVisible(isAuthenticated);
            } else {
                System.out.println("Usuario o contraseña incorrectos.");
            }
        } catch (IOException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_verificarMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_verificar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lb_contraseña;
    private javax.swing.JLabel lb_imagen;
    private javax.swing.JLabel lb_iniciarsesison;
    private javax.swing.JLabel lb_logo;
    private javax.swing.JLabel lb_slogan;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JLabel lb_verificar;
    private javax.swing.JPanel panel_der;
    private javax.swing.JPanel panel_izq;
    private javax.swing.JPasswordField pf_contraseña;
    private javax.swing.JTextField textf_usuario;
    // End of variables declaration//GEN-END:variables
}
